# Render README.RmD
name: Render readme

# Controls when the action will run.
#on:
#  schedule:
#    - cron:  '30 11 * * *'
# Controls when the action will run.
on: [push, pull_request]


jobs:
  run_rscripts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::data.table
          any::lubridate
          any::rjson
          any::flextable
          any::forecast
          any::ggplot2
          any::webshot
          any::rmarkdown

    # Run R script
    - name: Render README
      run: Rscript -e 'rmarkdown::render("README.Rmd")'

 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add *
        git commit -am "Re-build README.Rmd"
        git push
